Serde
zgtm/dementia pull request #3
Opened 2018-09-13 17:57 UTC by dpc

2018-09-13 17:57 UTC, dpc commented
This is on top of #2

2018-09-16 20:12 UTC, zgtm requested changes
These comments are meant for #3 and #4 simultaneously.

2018-09-16 20:12 UTC, zgtm commented on src/tests.rs
> +}
Shouldn't this file (together with `sync_example.json`) go into the `tests/` directory instead of `src/`?

2018-09-16 20:12 UTC, zgtm commented on src/sync.rs
> +pub struct SyncMsg {
I think we should drop the `Sync` prefix in all these type, since they're already in the `sync`-module (so this would basically by `sync::Msg`).

2018-09-16 20:12 UTC, zgtm commented on src/sync.rs
> +pub struct SyncRoomsJoinTimeline {
Do we need all those long names, here? A matrix timeline should look the same everywhere in the matrix specs, doesn't it? So `Timeline` would suffice (or if not, `JoinTimeline` should).

I noted some of the types were already renamed in #4 … This should be done consistently.

(On a side note; why has the matrix API documentation become so horrible to read and search in? o_o I can't find the definition of a timeline object in there. Am I missing something?)

2018-09-16 20:12 UTC, zgtm commented on src/sync.rs
> +    Message(SyncRoomsJoinTimelineEventMessageContentText),
Why not directly `Message(String)`?

Also this should be called `Text` (as already is in #4).

2018-09-17 01:15 UTC, dpc commented
At this point, it's not going to be very efficient to go back end forth with discussing this stuff. IMO you should just merge and modify, or throw away and write according to your own opinion and goals.

I won't have much more time to spend on this - I hacked my Matrix bot to the point I wanted it to be, and I will now have to take care of other Jira tickets. :)

2022-08-29 19:00 UTC, closed without merging